bin/ci-run
These require updating `administrate`: #360
The `puma` vulnerability will be patched by #363
=> ci: ignore unpatchable vulnerabilities for now

app/views/signs/card/_attachment.html.erb
revert the video_attributes change I made in the other CCSD-2064 branch because its SUPPOSED to not have thumbnails. The change made it have the wrong thumbnails
=> revert the video_attributes change I made in the other CCSD-2064 branch

spec/rails_helper.rb
Increase the capybara maximum wait time from 5 to 15 seconds, just in
case codeship CI is having a slow day
=> increase capybara wait time from 5 to 15 seconds

db/migrate/20191003003039_add_contributor_to_signs.rb
This users name was invalid, meaning it'd cause errors if we tried to link to their user profile.
So far this has only seemed to occur once, on UAT where someone had associated a comment to this user - while I believe that was an invalid state that could only be achieved via the rails console, for safety we've renamed the user to have a valid username after discussion with the client.
For safety and ease of conscience, I'm renaming the single reference to that username :)
=> chore: rename "Unknown Contributor" to have a valid username

package.json, yarn.lock
This doesn't fix the vulnerable version of `ws` being pulled in, but we'll need to upgrade anyway so might as well pull this up to the latest major ahead of time.
=> build: update `lighthouse` to v8

spec/rails_helper.rb
This probably won't too much of a difference, but the test suite typically takes 30-40 minutes to run so any speedup is a gain at this point.
=> test: disable animations to make things a little faster

yarn.lock
Dependabot seems confused over this one, so have done it manually
=> fix: update `ansi-regex` for security

yarn.lock
build(deps): bump loader-utils from 1.4.0 to 1.4.2 (#466)
Bumps [loader-utils](https://github.com/webpack/loader-utils) from 1.4.0 to 1.4.2.
- [Release notes](https://github.com/webpack/loader-utils/releases)
- [Changelog](https://github.com/webpack/loader-utils/blob/v1.4.2/CHANGELOG.md)
- [Commits](https://github.com/webpack/loader-utils/compare/v1.4.0...v1.4.2)
---
updated-dependencies:
- dependency-name: loader-utils dependency-type: indirect ...
Signed-off-by: dependabot[bot] <support@github.com>
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
=> staging -> production

yarn.lock
Addresses GHSA-3rfm-jhwj-7488
Addresses GHSA-76p3-8jx3-jpfq
Addresses GHSA-hhq3-ff78-jv3g
=> fix: update `loader-utils` for security

app/controllers/sign_video_comment_controller.rb, app/frontend/components/video-comment.js
This was added in https://github.com/ackama/nzsl-share/commit/3b4d2d441b0177046f68b8e283e3c8cacd099ba4 though I can't see any strong reason why so am going to see what happens if we just remove it.
(this is being flagged by https://github.com/ackama/nzsl-share/pull/452 which I'd really like to land, but want a better understanding before I mark it as ignored)
=> fix: enable csrf protection for create route

Aptfile
Heroku doesn't include SQLite dev packages. [They](https://devcenter.heroku.com/articles/sqlite3) and [everyone](https://stackoverflow.com/questions/66839571/how-to-use-sqlite-on-heroku) [else](https://stackoverflow.com/questions/31395856/django-deploying-an-application-on-heroku-with-sqlite3-as-the-database)  is adamant that it's not a good idea. 
In our case, we definitely want to do this. We have a bunch of relational data from Signbank, which we want to update every now and then, but not from within this application. SQLite gives us a performant data source for this data, with the ability to have relations between glosses, video and imagery information, as well as the ability to use native ActiveRecord mechanisms to access this data.
Fortunately, HashRocket has already had the same …
=> Add Aptfile to install SQLite3 dev dependencies

.github/workflows/codeql-analysis.yml
I just realised this'll actually take effect once its on `main`, so we don't even need to merge this into `production` 🎉
=> ci: update codeql target branch

app/views/topics/index.html.erb, spec/system/topics_feature_spec.rb
This is the first and most obvious step of NZSL-61 - add a 'See all signs' button to the top of the topics index page. This helps with discoverability, since if someone can't find an appropriate topic, they've got an obvious way to see all the signs.
I'm expecting to add an 'Other' topic type thing for this feature as well.
=> NZSL-61: Add 'See all signs' button to the top of the topics index page

.gitignore, CONTRIBUTING.md, Procfile, README.md, bin/setup, lib/tasks/dictionary.rake
This pull request adds a simple rake task to update the dictionary file stored in the repo to the latest version each time a web or worker dyno starts. I've tried to make this fault tolerant; that is, if anything goes wrong updating the dictionary DB, it falls back to the latest version (this uses some shell magic, which I've tested using `foreman start`, and I assume Heroku will handle this as well). 
In the future, we could move this into Github Actions. This would be nice because we would track changes to the dictionary, be able to PR changes, etc, however there's quite a high risk that we could quickly bloat the repo, since git treats SQLite as a binary file, so keeps a full copy of the file for each commit. For now, we're going to stick with this approach, since it allows us to play …
=> NZSL-47: Update dictionary when web or worker processes start

app/controllers/sign_comments_controller.rb, spec/requests/sign_comment_spec.rb
This bug occurs because the folder ID was reset when the edit comment form was submitted, since it didn't include the current folder ID. Rather than add a hidden field, I've opted to pull the folder ID from the existing comment, to avoid params tampering. 
https://user-images.githubusercontent.com/292020/207740037-3c6389e7-58ca-4a42-b05f-517cfabe61a7.mp4
=> NZSL-69: Retain the folder a comment is in when it is edited

app/controllers/sign_workflow_controller.rb, spec/system/sign_show_page_spec.rb
This PR fixes an error that occurred when redirecting after a moderator unpublishes or declines a sign. If a moderator performed these actions, the action is performed successfully but the app goes into a redirect loop. This happened because the app tried to redirect back to the sign after performing these actions, but the moderator no longer has permission to visit these signs. The code in ApplicationController that recovers from a permission error tries calling redirect_back. As redirect_back had a permission error that was attempted to be fixed by calling redirect_back, the app would get caught in an infinite loop.
This was fixed by updating the sign workflow controller so that the succeeded method can be passed a path. If a path is passed, then the app will try to redirect to the path …
=> NZSL-84 mod redirect error

Procfile, README.md, bin/setup, config/initializers/dictionary_sign.rb
This is more resilient than trying to intercept all process invocations. On
heroku, the deploy failed due to assets:precompile being run for example.
Instead, we can download the database each time the app starts, to make sure we
are using the most up-to-date version. Heroku will always update the most recent
version, since the database is gitignored so not present in the slug.
=> Update the dictionary if it is older than 1 month old when the application starts

app/controllers/topics_controller.rb, app/models/sign.rb, app/models/topic.rb, app/views/signs/show.html.erb, app/views/topics/index.html.erb, app/views/topics/show.html.erb, config/routes.rb, spec/models/sign_spec.rb, spec/system/sign_show_page_spec.rb, spec/system/topics_feature_spec.rb
This pull request wraps up NZSL-61:
* Adds a breadcrumb to signs without a topic, called 'Other signs'. This cannot be clicked on, but indicates that the sign doesn't have a topic. 
* Adds a link to the bottom of the topics list page - 'Other signs'
* Adds a 'uncategorised' action to topics controller to display any signs accessible to the signed-in user which don't have topics
=> NZSL-61: Display 'Other signs' in breadcrumbs for signs without topics, add to topics index page and other signs show page

.github/workflows/ci.yml
This is a bit weird, but @joshmcarthur has been having some GH API related failures for both the `check-with-osv-detector` action and with tests (as they download the sign db using the same method) - we suspect it's because of rate limiting, which we can check by inspecting the headers of a request made to the GH API (which is what this change has CI does when it fails)
=> ci: attempt to check rate limiting headers in the case of a error

app/controllers/admin/users_controller.rb, app/jobs/delete_user_job.rb, app/models/user.rb, app/policies/user_policy.rb, app/views/admin/users/_collection.html.erb, app/views/sign_comments/shared/_comment.html.erb, app/views/sign_comments/shared/_options.html.erb, config/locales/en.yml, db/migrate/20221218222106_allow_nil_sign_comments_user.rb, db/schema.rb, spec/jobs/delete_user_job_spec.rb, spec/policies/user_policy_spec.rb, spec/requests/admin_users_spec.rb, spec/support/shared_examples/administrate_shared_examples.rb, spec/system/edit_sign_feature_spec.rb, spec/system/sign_comments_spec.rb, spec/system/user_administration_spec.rb
This pull request implements user deletion, including taking care of related records:
* Private folders can just be destroyed
* The existence of signs attached to the user should prevent destruction
* Shared folders which are owned by the user being destroyed should be reallocated to the next available collaborator (who is not also the user)
* Sign comments should remain, but should be displayed anonymously
https://user-images.githubusercontent.com/292020/208327049-33f3a7c5-2dfe-446a-88cf-c235e7bbbeb4.mp4
=> NZSL-59: Allow users to be deleted

app/controllers/admin/signs_controller.rb, spec/system/edit_sign_feature_spec.rb, spec/system/sign_moderation_spec.rb
This pull request adds a default filter for `admin/signs#index`. There are a number of ways to accomplish this, but I've tried to put this in the most obvious place, which is the controller action. This causes the pending search filter to be applied, meaning that by default, an administrator will only see signs that require some action.
https://user-images.githubusercontent.com/292020/207745241-eb5e8860-5686-4373-8812-26f9cda79b0f.mp4
=> NZSL-63: Filter sign moderation to pending signs by default

.rubocop.yml, app/controllers/sign_comments_controller.rb, app/controllers/signs_controller.rb, app/models/sign_comment.rb, app/models/sign_comment_activity.rb, db/migrate/20221221033513_create_sign_comment_activities.rb, db/schema.rb, lib/tasks/dictionary.rake, spec/factories/sign_comment_activities.rb, spec/models/sign_comment_activity_spec.rb, spec/models/sign_comment_spec.rb, spec/requests/sign_spec.rb
This pull request implements the data structure and API to track views on sign comments. This API is called from `SignsController#show` as each page of comments is read. 
At this stage, this data is not used anywhere, however upcoming tasks will use the data to determine whether to indicate that there are unread signs on a comment.
=> NZSL-95, NZSL-96: SignCommentActivity model and tracking API

app/models/sign_comment.rb, app/models/user.rb
Two features collided. I added `SignCommentActivity`, which has a foreign key against `users`, which is violated when we attempt to destroy the user (NZSL-59). 
This is fixed by adding `dependent: : destroy` in the user model to make sure we delete any sign comment activities when we destroy a user. I also fixed a similar issue when removing a comment, where we should also remove any activity on the sign comment (if a comment is un-removed, this should count as a new comment)
=> NZSL-95: Destroy sign comment activity belonging to the user when the user is destroyed

app/controllers/signs_controller.rb, spec/requests/sign_spec.rb
This is really bad QA on my part :-/
If the user is not logged in, we shouldn't try and record sign comment activity, since obviously we need a user attached to this activity for it to be useful. Added a guard clause, and a test to assert that when the user is not signed in, it doesn't break the request, and doesn't record any activity.
=> Only record sign comment activity if a user is signed in

.github/workflows/ci.yml
Turns out that unauthenticated GH API requests are limited to 60 _per hour_ (I thought it was per minute) - the action only needs to talk to the GH API to figure out what the latest version of the detector is, so we can just provide a specific version instead.
The detector is pretty stable, so there shouldn't be any strong downside to this.
=> ci: use a specific version of `osv-detector` to avoid GH rate limiting

app/policies/sign_policy.rb, app/views/signs/show.html.erb, spec/policies/sign_policy_spec.rb, spec/system/sign_show_page_spec.rb
This PR fixes two issues Micky found in UAT:
* `SignPolicy::Scope` wasn't retaining existing where clauses on the scope passed to it, but was resetting the scope. This meant that when a moderator was signed in, viewing any topic would show all the signs they could access, not just the signs in that topic.
* The way we choose a topic to show in the breadcrumbs is...more complex than I thought. Basically if you have arrived on the sign page from a topic, we show that topic name as the breadcrumb. Otherwise we show the first topic that belongs to the sign. The fix for this was to fall back so that if the sign cannot resolve a topic from the referrer, it will use the first topic in the collection. In practical terms, this issue _mostly_ happened because of the above issue - normally, if your …
=> NZSL-61: Fixes for uncategorised topic signs

app/views/signs/new.html.erb, config/application.rb, spec/rails_helper.rb, spec/system/contribute_sign_feature_spec.rb, spec/views/signs/new.html.erb_spec.rb
This pull request implements a feature flag to allow us to select whether to use the Uppy file upload, or the older, "Legacy" file upload. I'm introducing this feature flag so that I can release iterations on the uppy implementation onto `main` rather than accruing a large changeset. This allows us to quickly flip the app into using one implementation or the other until we are ready to switch over, at which point we can remove the feature flag.
I'm expecting most of the Uppy code to be in JS for now, so the if condition just wraps a div using Stimulus-style controller attributes.
=> NZSL-68: Add a feature flag to use legacy or uppy file uploads

config/initializers/dictionary_sign.rb
Fixes a failed production build that we picked up specifically because we want to run production in Freelex mode for now, so we hadn't run this code path since refactoring to use `to_prepare`. 
Switching to `next` allows the guard clause to work correctly.
=> Must use 'next' instead of 'break' to guard within proc closure

.github/workflows/ci.yml
~See https://github.com/G-Rath/check-with-osv-detector/pull/2~
~If this works, I'll publish as v0.2.0 and then change this PR over to using that instead of a commit.~
This should hopefully allow us to not specify a specific version
=> ci: update `osv-detector` action

app/controllers/signs_controller.rb, app/frontend/components/_sign-card.scss, app/policies/sign_comment_policy.rb, spec/policies/sign_comment_policy_spec.rb, spec/requests/sign_comment_spec.rb, spec/requests/sign_spec.rb
1. Change indicator colour from royal blue to the orange accent colour
2. Recursively mark comment replies as read to make sure that viewing a comment with nested replies correctly clears the unread indicator
3. Resolve a scoping issue that overcounted comments when a sign was removed from a folder that it has comments for
=> NZSL-57: UAT feedback

.eslintrc.js, app/frontend/components/uppy-file-upload.js, app/frontend/components/uppy/ActiveStorageUpload.js
This pull request integrates Uppy with ActiveStorage direct uploads - each uploaded file sends a request to Rails to get the direct upload URL, then uploads directly to the service (disk locally, S3 when deployed).
There was a whole tree of forks for adding this as a library. Because no one fork was obviously maintained/going to receive patches, I thought it was best to vendor the plugin - it's only 200 lines, and a lot of that is boilerplate, just so that it's a little easier to understand and debug. I still had to make some updates to have it work with our version of Uppy.
With ActiveStorage integrated, we can now start incorporating the sign workflow - validating types and sizes, contribution limits, and actually creating the sign record after upload. …
=> NZSL-108: Integrate Uppy with ActiveStorage

app/frontend/components/create-sign-form.js, app/frontend/components/uppy-file-upload.js, app/views/signs/new.html.erb, spec/views/signs/new.html.erb_spec.rb
Wraps the file upload controller with a new controller with specific rules for sign videos. We'll need to implement one of these for each 'type' of upload (video comments, examples, editing sign video), just to handle the workflow each time. 
This new controller at this stage just enforces sign video rules - file size, type, and contribution limits. 
File size restriction:
https://user-images.githubusercontent.com/292020/214430431-f6227564-556c-40a9-8fd0-54d6cf481e9e.mp4
File type restriction:
https://user-images.githubusercontent.com/292020/214430535-9a9ff419-ab20-46ba-a375-8d85e346e441.mp4
Contribution limit restriction:
https://user-images.githubusercontent.com/292020/214430593-d41543c1-b417-4f16-88a9-435a90163ffa.mp4
=> NZSL-109: Add file size, contribution limit and type restrictions to Uppy for creating signs

app/policies/sign_comment_policy.rb
This prevents us counting comments on the sign when the user has access to a folder that a comment is in, but via a different sign to the one we are looking for comments on. I originally included this in the previous PR for NZSL-57, but removed it to save a query because I didn't think it was needed. It is actually needed, since not scoping the accessible signs affects the folders that are returned to us, which can affect the comment results.
=> NZSL-57: Respect existing scope when querying for comments

app/controllers/signs_controller.rb, app/frontend/components/create-sign-form.js, app/frontend/components/edit-sign-form.js, app/frontend/components/uppy-file-upload.js, app/frontend/components/uppy/signVideoRestrictions.js, app/services/sign_creator.rb, app/services/sign_updater.rb, app/views/signs/edit.html.erb, spec/requests/sign_spec.rb, spec/services/sign_creator_spec.rb, spec/services/sign_ownership_transfer_service_spec.rb, spec/services/sign_updater_spec.rb, spec/system/edit_sign_feature_spec.rb
This pull request is the first feature that uses Uppy without a fallback, since this is new functionality.
This presents Uppy in a modal after clicking "Change video" on a sign. This allows selection of a single file, and then updates the sign with the new video. When the video is submitted, we update the sign to re-queue the new video for processing (thumbnail generation and encoding).
This needed a bit of tidying up to make sure the creation and updating process is consistent in terms of the post-processing.  I'm aware that the create and update javascript for sign videos has quite a bit of replication. I had a few ideas about how to tidy this up, but none of them really worked out. Possibly with Stimulus wrapped around this functionality it could become slightly easier. …
=> NZSL-64: Update sign video for an entry

app/mailers/sign_workflow_mailer.rb, app/models/sign.rb, app/views/sign_workflow_mailer/declined.text.erb, app/views/sign_workflow_mailer/published.text.erb, config/locales/en.yml, spec/mailers/previews/sign_workflow_mailer_preview.rb, spec/mailers/sign_workflow_mailer_spec.rb, spec/models/sign_spec.rb
This PR adds emails that are sent to a sign's contributer when that sign is published or when it is declined.
=> NZSL-65 Added emails for publishing and declining signs

config/sidekiq.yml
Since we didn't have this queue active, we were destroying blobs, but not their underlying files. This doesn't really impact the application functionality, but means we're storing files unnecessarily.
This change adds the purge queue to the list of queues that Sidekiq will work off, so we can correctly purge unused files.
=> Add active_storage_purge queue to the list of queues Sidekiq will work off

app/views/sign_workflow_mailer/declined.text.erb, app/views/sign_workflow_mailer/published.text.erb, spec/mailers/sign_workflow_mailer_spec.rb
A small wording change for sign workflow email templates to use language consistent with how DSRU/NZSL Share refers to signs.
Approved:
```
Kia Ora patrick4
Your sign ‘Reuben’ has been approved, it has now been published.
If you have any questions, please contact test@example.com.
Kind regards
NZSL Share Team
NZSL Share: https://nzslshare.nz
NZSL Online Dictionary: https://nzsl.nz
Learn NZSL: http://www.learnnzsl.nz
Email: DSRU@vuw.ac.nz
```
Declined:
```
Kia Ora minerva8
Your sign ‘Warner’ has been declined.
If you have any questions, please contact test@example.com.
Kind regards
NZSL Share Team
NZSL Share: https://nzslshare.nz
NZSL Online Dictionary: https://nzsl.nz
Learn NZSL: http://www.learnnzsl.nz
Email: DSRU@vuw.ac.nz
```
=> NZSL-65: Adjust wording for accepted/declined mailer templates

app/frontend/components/_sign-table.scss, app/views/signs/table/_row.html.erb
This pull request implements the contributor information from Figma. It's basically a bunch of Flexbox to have a 2-column layout (icon + info) that unwraps into a single line on small screens. The method to add a divider between the two info elements (username + date), but I was already upset about the amount of classes for this. Happy to take feedback if it looks _too_ gross. Same reason for negative margin on mobile - I just needed to pull the element up a little. Probably with design feedback, we should reduce the cell padding right across the cells, and then increase it just where necessary.
Small/medium:
Large:
=> NZSL-126: Implement contributor information

app/frontend/foundation/_settings.scss, app/views/signs/table/_controls.html.erb
This PR adds utility classes to the assign button to stack it to full-width on small screens
On larger screens, the existing behaviour is retained
=> NZSL-128: Stack Assign button on small screens

app/frontend/components/_sign-table.scss, app/frontend/foundation/_settings.scss, app/views/signs/table/_controls.html.erb
This PR updates the styling of the submit for publishing button based on feedback from Karyn.
This includes the following changes
- Updating the width of the button on mobile to 100% (through the use of the cell class)
- Updating the width of the button so that it matches the width of the sort dropdown above it (not something Karyn specifically gave feedback on but it better matches the designs and is a side effect of setting the width for small screens while trying to minimize the number of new classes)
- Adding a margin above the button to seperate it from the bulk assigning topics controls (this is done because in another story, they will be stacked vertically on mobile)
=> NZSL-129 Updated submit for publishing button styles

app/controllers/sign_batch_operations_controller.rb, config/locales/en.yml, spec/requests/sign_batch_operations_spec.rb, spec/system/my_signs_spec.rb
Adds messaging for complete success:
Partial success:
Failure:
When no signs are selected:
=> NZSL-131: Improve bulk sign operation messaging

app/frontend/foundation/overrides/buttons.scss, app/views/signs/table/_controls.html.erb
This is the last piece of design feedback for NZSL-101. Changes the button style from neutral (which was meant to be disabled state, something not clear in Figma), which is now unused and can be removed.
Also adds data-disable-with so that the buttons are not clickable while the form is submitting. I've cleared with Karyn that _both_ buttons disable when submitting.
https://user-images.githubusercontent.com/292020/220217324-675b7253-e813-41c4-b5f0-6761be7d5afa.mp4
=> Remove neutral button style, switch to primary, and add disabled button style while submitting

config/application.rb
In Rails 7, the hash digest class was changed from SHA1 to SHA256, which means that our variant keys started generating with slightly different signatures. 
This change reverts the hash class to SHA1 so that our existing encoded videos keep a stable signed ID and continue to work without being re-encoded.
There's probably not a good case for figuring out how to update to SHA256, other than that we've now diverged from the Rails 7 framework default, and other similar changes in the future could break in the same way. We would probably have to refactor `CachedVideoTranscoder` to use ActiveStorage less deeply, in the hope that we wouldn't need to care about the key to this level.
=> Revert ActiveSupport::KeyGenerator.hash_digest_class from SHA256 to SHA1 to keep our variant signatures stable

app/frontend/components/_home-main.scss, app/frontend/components/_sign-requests.scss, app/views/home/index.html.erb, app/views/sign_requests/index.html.erb
This PR addresses two pieces of feedback on the sign requests page and the home page
1. Update the links on the homepage to match updated designs
2. Update the requests page to move the footer into the header
=> NZSL-134 Addressed requests page design feedback

app/presenters/sign_presenter.rb, spec/presenters/sign_presenter_spec.rb, spec/system/edit_sign_feature_spec.rb, spec/system/sign_show_page_spec.rb
We've experienced some problems with sign videos being unplayable, because while thumbnails have generated, the sign video has not (or it has, but we have not received the callback so have not updated the `processed_videos` flag on the Sign.
This pull request tightens the critieria for us showing the video poster to require the videos to be processed. This will surface signs that don't have playable videos more easily, allowing us to see these easily and try and track down _why_ they are not processed. Currently, it's quite hard to discover broken signs otherwise, since it requires someone to click the video and see that it does not play - the doing of which queues a video transcode for the missing video, and 'fixes' the sign (even though it is still not fully processed).
=> Require sign videos to be processed before we show the video OR thumbnails

Procfile
Excerpts:
- WARNING: don't ever use a concurrency value greater than 10 without thorough testing.
- I don't recommend setting Sidekiq's concurrency greater than 10. At larger values, you will see poor performance due to CPU contention. With 1x and 2x dynos, I would set concurrency to 5.
From https://github.com/sidekiq/sidekiq/wiki/Heroku
It's possible that we need to optimise how we download and process videos, however reducing the concurrency from the default value of 25 should help.
=> Follow Sidekiq's concurrency recommendation for running on 1x dynos on Heroku

app/frontend/components/_sign-card.scss, app/frontend/components/uppy-file-upload.js, app/frontend/foundation/_settings.scss, config/application.rb, spec/system/edit_sign_illustrations_spec.rb, spec/system/edit_sign_usage_examples_spec.rb
This pull request makes some simple improvements to how videos are presented in NZSL Share:
1. If we are displaying an official dictionary sign, display this in 4x3 ratio, not 16x9 - the dictionary videos are mostly (not 100% exclusively) 4x3, so using this aspect ratio in Share prevents black bars on these videos to force them to 16x9, and also means that they are slightly larger so easier to see.
2. Uppy allows us to specify media track constraints when recording a video, one of which is our preferred aspect ratio. I've set this to 16x9, since this is the display aspect ratio for NZSL Share. I'm hoping this will resolve some device-specific issues we've encountered where, without a constraint specified, a video will be recorded in 4:3 even if the camera hardware supports 16:9. This is …
=> Improve behaviour of aspect ratios when presenting videos

.osv-detector.yml
This PR ignores the vulnerability in postcss 7 as we are not currently able to upgrade it to postcss 8 in order to fix this. The ignored vulnerability can be found here - [GHSA-7fh5-64p2-3v2j](https://github.com/advisories/GHSA-7fh5-64p2-3v2j)
=> Ignore postcss 7 vuln (GHSA-7fh5-64p2-3v2j)

app/services/signbank_export.rb, spec/factories/sign.rb, spec/services/signbank_export_spec.rb
This PR adds more info to the signbank export based on Micky's comments on NZSL-75. This includes the following:
- Contributer username
- Contributer email address
- Time of sign upload
- Agree and disagree counts
- Comments (including both the username and the comment itself)
Here is Micky's table
=> NZSL-73 Added extra content to signbank export

yarn.lock
Resolves GHSA-jchw-25xp-jwwc. Updating to beat dependabot to fix the build on PRs.
=> Update follow-redirects to 1.15.4 to resolve GHSA-jchw-25xp-jwwc

app/models/dictionary_sign.rb, app/views/application/_footer.html.erb, spec/views/application/_footer.html.erb_spec.rb
This pull request adjusts the footer to display the user_version PRAGMA value from the released dictionary database. This allows users to see what version of the data is being used. This is especially handy to check that the data has been updated, and to check what version of data is used if an issue is noticed.
=> NZSL-163: Display the dictionary database version in the application footer

config/initializers/dictionary_sign.rb, example.env, lib/tasks/dictionary.rake
This pull request modifies the boot process of NZSL Share to download a file from a specified S3 location. This can be a public or private S3 object, and the URI is specified using an environment variable. We attempt to download from the public location first, then attempt to generate a presigned URL and download from that. If no keypair is present and the public URL is not accessible (e.g. this is a prerelease database), then the app continues to boot, but without a dictionary database. 
I'm expecting to provide a similar patch to https://github.com/odnzsl/nzsl-online. We might consider extracting this common code into a Rubygem at some point, since we fairly regularly end up duplicating code.
=> NZSL-160: Pull Signbank dictionary database from a public or private S3 location

app/views/application/_footer.html.erb
I added this several years ago, I now disagree with myself. Caching the template without any key parts to expire doesn't really add a lot. Template rendering of a largely static template should be just as fast or faster than retrieving from a cache, and specifically this stops the database version from showing the correct value.
=> Remove footer cache without any expiring key fragments

app/models/dictionary_sign.rb, spec/models/dictionary_sign_spec.rb
Technically, all signs should have a main video. Due to prerelease exports though, data that we have previously assumed to be present can actually be missing, so the guard clause here needs to check for nil OR empty string.
=> Increase guard clause to also bail out when the video URI is an empty string

app/services/signbank_export.rb, db/migrate/20240116022132_remove_description_from_signs.rb, db/schema.rb, spec/factories/sign.rb, spec/services/signbank_export_spec.rb
This field was included in the signbank export, which is how we noticed it was still there. It appears that it was [added](https://github.com/ackama/nzsl-share/commit/87e78384725d024013acbec3e9a258fb7d0f1654) to an early data modelling commit, and subsequently superseded by notes and usage examples. It's not used in any view, dashboard, presenter or anywhere else that I can see, so to avoid confusion, should be removed.
=> Remove unused 'description' field from signs

app/controllers/sign_attachments_controller.rb
We have a constraint at the route level which means this isn't an actual vulnerability but it's still not nice to have in a controller so lets be explicit instead.
I've _not_ included any tests since this can't actually be triggered due to the routing constraint, but that should be fine since this will catch if the constraint ever changes.
=> refactor: avoid using `public_send` in attachments controller

.osv-detector.yml
Patching GHSA-wr3j-pwj9-hqq6 requires a major upgrade to webpacker/shakapacker which we're not ready to take on yet - we can ignore the advisory in the meantime as it is only being used for local development.
=> chore: ignore `webpack-dev-middleware` advisory

app/services/signbank_export.rb, spec/services/signbank_export_spec.rb
This PR adds sign ids to the signbank export. These are used by signbank to filter out signs that have already been imported. The PR that adds the filtering out of signs with matching ids is implemented in signbank here: https://github.com/ODNZSL/NZSL-signbank/pull/159
Here is a truncated sample export from the development environment
[signbank(14).csv](https://github.com/ackama/nzsl-share/files/14859555/signbank.14.csv)
=> NZSL-186 Export ID with signbank export

.osv-detector.yml
Currently there is no patch for the security advisory https://github.com/advisories/GHSA-2p57-rm9w-gvfp
=> chore: ignore unpatchable ip vulnerability

package.json, yarn.lock
Newer versions of lighthouse are always better and this helps ensure we can apply the latest security patches - we can't go any higher than v10 right now because v11 required Node v18 or higher but this is still an improvement and we plan to upgrade Node later this year
=> ci: upgrade `lighthouse` to v10

.github/workflows/ci.yml, bin/ci-test
These are the default [since v4.0.0](https://github.com/presidentbeef/brakeman/blob/main/CHANGES.md#400---2017-09-25).
The actual motivator for this is that it brings the line under 80 characters so Prettier is happier, but also really we should be using `config/brakeman.yml` for these settings to ensure all brakeman calls are consistent by default (I've not added that though because I have not seen evidence that brakeman is in the habit of changing its defaults often, so I don't think we need to worry)
Also see https://github.com/ackama/rails-template/pull/521
=> ci: omit default brakeman flags

package.json, yarn.lock
This is the current latest version of Foundation, which in theory is more compatible with Dart Sass, though in reality I'm not actually sure it has resolved any of the deprecation warnings we're getting - it's still good to be on the latest version though
=> feat: upgrade `foundation-sites` to v6.8

.osv-detector.yml
These will get patched soon, but in the meantime I want to have my PRs getting the green tick + I think this might actually be blocking deployments via Heroku
=> chore: update osv-detector ignores

app/models/user.rb, app/views/users/registrations/edit.html.erb, app/views/users/registrations/new.html.erb
`\A` and `\Z` are not valid in JS regexp, so currently our frontend validation isn't doing anything
=> fix: use a valid javascript regexp for username validation

config/initializers/dictionary_sign.rb
Downloading the database blocks all other actions including consuming exit signals and is compounded by seemingly being able to get triggered multiple times in quick succession even though the reloader only seems to get called once - I think what happens is that after making a change reloading the page triggers a reload cycle for every request and thus multiple sequential database downloads?
Ultimately we can avoid slowing down local development by only (re)downloading the database if its more than a month old or does not exist which ironically matches the behaviour currently described in the readme anyway
=> chore: don't try to re-download the database on every reload

babel.config.js, yarn.lock
This updates all of our babel dependencies to the latest versions allowed by their constraints, as part of reducing the diff with #653 and hopefully make it easier to identify why the drag-and-drop specs are failing
=> build: update babel dependencies to latest

README.md
(this is actually to trigger Heroku to do another deployment because the last one apparently failed due to an error on their side, but I think it was just the ubuntu-24 stack switchover being flakey)
=> docs: update README to reflect actual Rails version

.eslintrc.js
These patterns are pulled from `eslint-config-ackama`, and importantly include directories like `public/packs` which current get linted locally
=> chore: update eslint ignore patterns to exclude common generated files and directories

Gemfile.lock, package.json, yarn.lock
Being on the latest version of `lighthouse` is always a good idea and lets us patch some security vulnerabilities
=> test: upgrade `lighthouse` and `lighthouse-matchers`

app/frontend/application.scss
As far as I can tell this isn't required anymore which doesn't surprise me since we've upgraded webpack and a lot of other parts of the build pipeline - ultimately, it's getting flagged in the latest version of `stylelint` which we'll need to upgrade to address some security vulnerabilities
=> refactor: remove unneeded extension on scss import

package.json, yarn.lock
The current version we're using technically isn't compatible with the version of ESLint we're using, so upgrading fixes this
=> chore: upgrade `eslint-plugin-react` to address peer dependency mismatch

app/models/sign.rb, config/application.rb
These are not actually exploitable security vulnerabilities but they're being flagged by CodeQL and are subtle gotchas so we might as well address them
=> fix: ensure regular expressions are anchored

Gemfile, Gemfile.lock
The new version with official support for Sidekiq v7 has been released so we no longer need to pull from the git repository
=> chore: update `sidekiq-batch` to latest RubyGem version

.github/workflows/ci.yml
Not having this installed seems to be the cause of the recent consistent CI failing on the drag-and-drop tests about the sign not being found, and also addresses a bunch of constant redefinition warnings.
~While the test suite does pass with this, I would like confirmation from someone that knows the application better that we do expect to be using vips rather than mini_magick, as I can't find any reference to a preference or expectation in the codebase and I have found some GitHub issues suggesting there was a bug or two related to `image_processing` and Rails 7.0 having "default confusion".~ - I discussed with @joshmcarthur and he thinks this is fine
=> ci: install `libvips42`

spec/system/edit_sign_illustrations_spec.rb, spec/system/edit_sign_usage_examples_spec.rb
Currently these system specs consistently fails about not being able to find the sign, which I suspect is due to a race condition that I can't pin down, but having the sign always be created before the examples run seems to resolve it
=> test: always create sign before running spec examples

.osv-detector.yml
These have been patched via #684
=> chore: remove patched advisories from ignore list

.osv-detector.yml
We're currently blocked on patching this by https://github.com/GoogleChrome/lighthouse/pull/16215
=> chore: update config ignores

config/initializers/sidekiq.rb
Heroku Redis uses a self-signed certificate meaning we shouldn't try and validate the certificate.
Also see https://help.heroku.com/HC0F8CUS/redis-connection-issues
=> fix: don't verify redis SSL certificate for sidekiq

app/models/video_encoding_preset.rb
We've had a few failures in processing video files which have come from QuickTime, and it turns out to be that there's a colorspace difference that we need to account for; from our research, it doesn't seem that there's a significant downside to doing this regardless of where the video actually came from 🤷
=> fix: add a few more ffmpeg arguments to ensure compatibility with QuickTime/HEVC

yarn.lock
=> fix: update `cross-spawn` for security

yarn.lock
=> fix: update `path-to-regexp` via `express` for security

.osv-detector.yml, yarn.lock
We need to upgrade `@uppy/core` and co to be able to address the remaining instance, which [will require some brain thinking](https://github.com/ackama/nzsl-share/pull/661#issuecomment-2263921132) so for now I'm just marking it as ignored so we can do a deployment to production
Addresses some of GHSA-mwcw-c2x4-8c55
=> fix: update `nanoid` for security

babel.config.js, package.json, yarn.lock
This is based on the configuration we have in `rails-template`, and also ensures that GHSA-968p-4wvh-cqc8 is patched
=> build: update and modernize babel config

.github/workflows/ci.yml, .github/workflows/deploy_to_heroku.yml
This PR switches us to using the Heroku CLI for deployments to be consistent with our other codebases and so that deployments can be automatically tracked in Mahi
=> CC-2445: use heroku-cli for deployments 

Gemfile.lock
net-imap@0.5.6 is affected by the following vulnerabilities:
GHSA-j3g3-5qv5-52mj: net-imap rubygem vulnerable to possible DoS by memory exhaustion (https://github.com/advisories/GHSA-j3g3-5qv5-52mj)
=> fix: update net-imap for security

config/app.yml, config/application.rb, config/environments/production.rb
I forgot to replace secrets with app when I upgraded to rails 7.2, and secrets was deprecated in 7.1, and the deployment to testing is failing because its trying to read vars from secrets which no longer exist
=> CC-2379 Replace secrets with app, as secrets were deprecated in rails 7.1

yarn.lock
=> fix: update `brace-expansion` for security

spec/system/approved_user_application_spec.rb
These specs currently fail semi-frequently since there is no actual guarantee that the emails will be in the same order every time, so I've rewritten the tests to select all emails with the expected `to` address
=> test: make mail checks in system specs less flakey
