ackama/nzsl-share

app/views/signs/card/_attachment.html.erb
app/views/signs/show.html.erb

Use the foundation grid classes to ensure the videos are properly

CCSD-2064/dont show a poster for usage videos

---

Gemfile
Gemfile.lock
app/dashboards/sign_dashboard.rb
app/policies/approved_user_application_policy.rb
app/policies/comment_report_policy.rb
app/policies/user_policy.rb
lib/administrate_ext/search.rb

I'm tentative hopeful about how easy this was, but let's see what CI has to say...
This is required in order for us to be able to update Rails in order to patch some CVEs.

feat: update `administrate`

---

app/views/admin/approved_user_applications/index.html.erb
app/views/admin/comment_reports/index.html.erb
app/views/admin/signs/index.html.erb
app/views/admin/topics/index.html.erb
app/views/admin/users/index.html.erb

https://github.com/thoughtbot/administrate/pull/1725
https://github.com/thoughtbot/administrate/issues/1957
Relates to CC-1225

fix: update pagination to to use new `param_name` for administrate

---

Gemfile.lock
config/brakeman.ignore

Brakeman is currently failing due to https://github.com/presidentbeef/brakeman/issues/1603

fix: update `brakeman` to fix loofah detection bug

---

lib/tasks/bulkupload.rake

Bulk video uploads from s3 as a rake task, not super configurable at run time yet but it was quick to write!

Ccsd 1255/bulk video uploads

---

yarn.lock

This removes a security vulnerability

fix: update `webpack-dev-server` for security

---

Gemfile
Gemfile.lock
spec/spec_helper.rb

Set up rspec-retry to avoid whole-suite failures due to intermittent test fails

---

.simplecov
spec/spec_helper.rb

Use .simplecov to configure simplecov

---

spec/system/styleguide_feature_spec.rb

Remove styleguide spec, which takes up 30s of test run time all on it's own and doesn't even test a real page

---

Gemfile.lock
yarn.lock

Releases some security updates

staging -> production

---

package.json
yarn.lock

Addresses GHSA-pfrx-2q88-qq97 (indirectly)

fix: update `lighthouse`

---

package.json
yarn.lock

* fix: update `lighthouse` (#458)

uat -> production

---

.github/workflows/ci.yml
.osv-detector.yml
package.json

GitHub Actions is free for open-source projects, so we can use it to greatly parallelise CI which is great since it currently takes 30m+ 😅
(I'm starting with running the whole suite in one job, but will break it up to be across multiple jobs once I've gotten it working)
(I've disabled CodeShip for this branch)

ci: setup github actions workflow

---

.github/workflows/codeql-analysis.yml

Actions + Code Scanning is free for public / oss repos, so let's start using that!

ci: setup code scanning workflow

---

.github/workflows/ci.yml
yarn.lock

Security updates related to json5 and an update to installation for CI that fixes an issue where some packages were not found

Security updates

---

app/presenters/sign_presenter.rb
spec/presenters/sign_presenter_spec.rb

This pull request addresses another case where sign comments are miscounted. In this scenario, a sign is published, with comments placed on it, then made private again (via "Unpublish" on the sign edit page). While the comments on the public sign are correctly hidden, the sign card indicator continues to count these comments.
This change adds an additional scope to the sign presenter to only consider comments that were added when the sign was in a particular state - most of the time, this is "private" or "published". This means that comments added when the sign is public are discounted if the sign is then unpublished, making the count correct.

NZSL-57: When scoping comments, require comments to have the same status as the sign status

---

.osv-detector.yml
yarn.lock

Addresses https://github.com/advisories/GHSA-c2qf-rxjj-qqgw

fix: update `core-js-compat`

---

app/views/signs/index.js.erb

On successful ajax, rebind foundation to new elements, so that when the user hits the "folder" button the folders popup shows

On successful ajax, rebind foundation to new elements

---

app/views/signs/index.js.erb

On successful ajax, rebind foundation to new elements, so that when the user hits the "folder" button the folders popup shows

On successful ajax, rebind foundation to new elements (#613)

---

.github/workflows/codeql-analysis.yml

I don't actually know what part broke but we're getting errors about the workflow not running right so I just regenerated it from the UI to make sure we're up to date

ci: update `codeql` workflow

---

Gemfile.lock

fix: update `rexml` for security

---

.eslintrc.js
app/frontend/packs/administration.js
app/frontend/packs/application.js
app/frontend/packs/contributions.js
app/frontend/packs/videocomment.js
package.json

This ensures that we're being consistent with our javascript

refactor: apply eslint to all js files

---

app/views/application/styleguide.html.erb
app/views/approved_user_applications/_fields.html.erb
app/views/approved_user_applications/new.html.erb
app/views/sign_requests/index.html.erb
app/views/signs/table/_row.html.erb
app/views/users/registrations/edit.html.erb

These were reported by my IDE so I fixed them

fix: clean up html a little

---

package.json
yarn.lock

None of these are actually being used nor are they part of our conventional eslint setup

chore: remove unused eslint configs and plugins

---

.stylelintrc.js
app/frontend/components/_footer.scss
app/frontend/components/_header.scss
app/frontend/components/_navigation.scss
app/frontend/components/_sign-card.scss
app/frontend/components/_video.scss
app/frontend/foundation/_settings.scss
app/frontend/foundation/overrides/base.scss
app/frontend/foundation/overrides/buttons.scss
app/frontend/foundation/overrides/form-labels.scss
package.json
yarn.lock

This addresses some security vulnerabilities and also aligns up with the latest config in `rails-template`
Addresses GHSA-7fh5-64p2-3v2j
Addresses GHSA-w5p7-h5w8-2hfq

refactor: upgrade `stylelint` and co

---

spec/system/contribute_sign_feature_spec.rb
spec/system/edit_sign_illustrations_spec.rb
spec/system/edit_sign_usage_examples_spec.rb

What's to bet these are the source of all the flake...

test: properly disable javascript for cases

---

.osv-detector.yml
yarn.lock

fix: update `lighthouse` and `express` for security

---

yarn.lock

fix: update `compression` and `on-headers` for security
